spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist = true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: b5c8cf8d-df92-4429-bb9b-21e195e61d61
  expiration: 9999999